### ISSUE TITLE
表面上是web服务器实际上是通过web的形式执行cli的php

### ISSUE THREAD

**Issue by jin123456bat** [zhenbianshu/tinyServer#1]
例如$_POST等超全局变量就没办法使用

**Comment by jin123456bat** [comment]
文件类型的资源没办法使用

**Comment by zhenbianshu** [comment]
nginx的功能就是受理请求然后再把请求分发出去，静态文件直接返回，php则分发到php-fpm。。。
因为不想再写个类似fpm的后台进程，所以用cli模式代替了。
但原理是相似的，cli模式通过标准输出STDOUT来交换数据，而nginx和fpm使用 uninx domain sockets 或 net sockets。
